import { Food } from './Food';

export const FOODS: Food[] = [
  {
    name: 'Protein Powder',
    cal: 160,
    nutrients: [{ name: 'Protein', intake: 25 }],
    serving: 1,
    per: 'scoop',
  },
  {
    name: 'Nutritional Yeast',
    cal: 80,
    nutrients: [{ name: 'Carbohydrates', intake: 100 }],
    serving: 1 / 4,
    per: 'cup',
  },
  {
    name: 'Fish Oil',
    cal: 40,
    nutrients: [{ name: 'Omega 3', intake: 3 }],
    serving: 1,
    per: 'tsp',
  },
  {
    name: 'Coconut Oil',
    cal: 40,
    nutrients: [{ name: 'Fat', intake: 9 }],
    serving: 2,
    per: 'tsp',
  },
  {
    name: 'Hemp Hearts',
    cal: 180,
    nutrients: [
      { name: 'Fat', intake: 15 },
      { name: 'Omega 3', intake: 2.5 },
      { name: 'Carbohydrates', intake: 1 },
      { name: 'Fibre', intake: 1 },
      { name: 'Sugars', intake: 1 },
      { name: 'Protein', intake: 10 },
      { name: 'Potassium', intake: 7 },
      { name: 'Calcium', intake: 2 },
      { name: 'Iron', intake: 22 },
      { name: 'Thiamine', intake: 25 },
      { name: 'Riboflavin', intake: 4 },
      { name: 'Niacin', intake: 10 },
      { name: 'Folate', intake: 11 },
      { name: 'Phosphorous', intake: 36 },
      { name: 'Magnesium', intake: 48 },
      { name: 'Zinc', intake: 27 },
      { name: 'Manganese', intake: 100 },
    ],
    serving: 3,
    per: 'tbsp',
  },
  {
    name: 'Normal Eggs',
    cal: 160,
    nutrients: [
      { name: 'Fat', intake: 11 },
      { name: 'Carbohydrates', intake: 1 },
      { name: 'Protein', intake: 13 },
      { name: 'Cholesterol', intake: 400 },
      { name: 'Sodium', intake: 130 },
      { name: 'Potassium', intake: 3 },
      { name: 'Calcium', intake: 4 },
      { name: 'Iron', intake: 10 },
    ],
    serving: 2,
    per: 'large eggs',
  },
  {
    name: 'Brown Eggs',
    cal: 160,
    nutrients: [
      { name: 'Fat', intake: 11 },
      { name: 'Carbohydrates', intake: 1 },
      { name: 'Protein', intake: 13 },
      { name: 'Cholesterol', intake: 400 },
      { name: 'Sodium', intake: 130 },
      { name: 'Potassium', intake: 3 },
      { name: 'Calcium', intake: 4 },
      { name: 'Iron', intake: 10 },
      { name: 'Vitamin A', intake: 22 },
      { name: 'Vitamin C', intake: 22 },
      { name: 'Vitamin D', intake: 8 },
      { name: 'Biotin', intake: 133 },
      { name: 'Choline', intake: 75 },
    ],
    serving: 2,
    per: 'large eggs',
  },
  {
    name: 'Pita Bread',
    cal: 160,
    nutrients: [
      { name: 'Fat', intake: 1.5 },
      { name: 'Carbohydrates', intake: 30 },
      { name: 'Fibre', intake: 5 },
      { name: 'Sugars', intake: 1 },
      { name: 'Protein', intake: 7 },
      { name: 'Sodium', intake: 250 },
      { name: 'Calcium', intake: 2 },
      { name: 'Iron', intake: 10 },
    ],
    serving: 1,
    per: 'pita/66 g',
  },
];
